version: 0.2

phases:
  pre_build:
    commands:
      - npm install --global yarn
      - yarn
      
  build:
    commands:
      - echo "Building..."
      - yarn install
      - yarn build
      - aws s3 sync build/ s3://ops-panel/